#cloud-config
hostname: master

users:
  - name: awolde
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCupU7f2tOd+88jyUHg0JrB2oHFNKV1Pl+wnJzMAv35zM3EZtYrMmv2B4oLDFa9Mjd3+r34DPnWR5Gw6brxOgiZ0GdvhNA9iuKpvcxkRRQTLX5JHy9dRxrvljpEGPnDRFKrS2ADYTv2yHbOkJNc8QHF1gype0Vw5sfM+1cPSvVj7YhIGRn+NqQMbbpcMcBm8woVK96rBdYDHBWXboWyJUIKYsPD325l1UtM8AsMlHrEGXu0P0moqfYSYxYWak0DATwdHKwXJsSm5m2g+kECB4dbKHNhIUjWA/cEw7gaLoUaXOESHdyfxftn/6DGtlh7HCFe/dq36YladYzwvslJOhT/ awolde
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDdeAsy3SpMUjWzvPViMJgI5JZYizekb/fgKUvMdg56R7SCKoYCmDgtmxgooD+iY6HJrb5ptDxCsJ14xullfFpqMGRsWs9sxYLT63OZsgJotnVG3QHNAH9BhmEGPNEGFXqbMOfVVK7PEQ1z9VXAJrrKLpIFwWpVOT7RFtqbiLN/1MnWOep7lKzrxxkc0x6lEhczns37egD9U8Wh5KaKNXPARAC+4olmlvMALnyX0k12/84gCD8wF/w7Y6U9Lz7lBYziQJ10I66J544GvRawiUAyc0iUBjV2fKo3D5o1zuyCNqFmwQvMPwWsoZiTN966aBhCxsrGDy4rmoZ0IaViIuit awolde
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash

packages:
  - jq
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - apt-transport-https

runcmd:
  - cat <<EOF | tee /etc/sysctl.d/k8s.conf
  - net.bridge.bridge-nf-call-ip6tables = 1
  - net.ipv4.ip_forward = 1
  - net.bridge.bridge-nf-call-iptables = 1
  - EOF
  - sysctl --system
  - mkdir -p /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - cat <<EOF | tee /etc/apt/sources.list.d/docker.list
  - deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable
  - EOF
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  - curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
  - cat <<EOF | tee /etc/apt/sources.list.d/kubernetes.list
  - deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
  - EOF
  - apt-get update
  - apt-get install -y kubelet kubeadm kubectl
  - apt-mark hold kubelet kubeadm kubectl
  - rm /etc/containerd/config.toml
  - systemctl restart containerd
  - swapoff -a
  - kubeadm init > init.log
  - cat init.log
  - cat << EOF | tee /etc/cni/net.d/10-containerd-net.conflist
  - '{ "cniVersion": "0.4.0", "name": "containerd-net", "plugins": [{"type": "bridge", "bridge": "cni0", "isGateway": true, "ipMasq": true, "promiscMode": true, "ipam": { "type": "host-local", "ranges": [ [ { "subnet": "10.88.0.0/16" } ], [ { "subnet": "2001:db8:4860::/64" } ] ], "routes": [ { "dst": "0.0.0.0/0" }, { "dst": "::/0" } ] } }, { "type": "portmap", "capabilities": { "portMappings": true } } ] }'
  - EOF
  - mkdir -p /home/awolde/.kube
  - cp -i /etc/kubernetes/admin.conf /home/awolde/.kube/config
  - chown awolde:$(id -g) /home/awolde/.kube/config

final_message: "The system is finally up, after $UPTIME seconds"